In [1]:
import pandas as pd

In [2]:
notaSemillero=pd.DataFrame({'NOMBRES':['Pedro', 'Darden', 'LeidyDarden'], 
                            'SEMESTRE' : [10, 7 ,8] ,
          
                            })
notaSemillero['Nota1']=3
notaSemillero
notaSemillero['Nota2']=[3.1, 4.2, 3.3]
notaSemillero
#print(notaSemillero)

       NOMBRES  SEMESTRE  Nota1  Nota2
0        Pedro        10      3    3.1
1       Darden         7      3    4.2
2  LeidyDarden         8      3    3.3

In [3]:
notaSemillero['Nota2']=[3.1, 4.2, 3.3]
notaSemillero

       NOMBRES  SEMESTRE  Nota1  Nota2
0        Pedro        10      3    3.1
1       Darden         7      3    4.2
2  LeidyDarden         8      3    3.3

In [4]:
notaSemillero.insert(1, 'CIUDAdd',['Manizales', 'Pereira', 'Aguadas'] )
notaSemillero

       NOMBRES    CIUDAdd  SEMESTRE  Nota1  Nota2
0        Pedro  Manizales        10      3    3.1
1       Darden    Pereira         7      3    4.2
2  LeidyDarden    Aguadas         8      3    3.3

In [5]:
notaSemillero.assign(DEPARTAMENTO=['Caldas', 'Risaralda', 'Caldas'] )
notaSemillero

       NOMBRES    CIUDAdd  SEMESTRE  Nota1  Nota2
0        Pedro  Manizales        10      3    3.1
1       Darden    Pereira         7      3    4.2
2  LeidyDarden    Aguadas         8      3    3.3